### PR TITLE
Ignoring all files generated by CocoaPods and Bundler and removing them from the repository.

### PR DESCRIPTION
**Pull request by irodrigo17**

### CODE REVIEW

**Comment by duemunk** [comment]
This has been dismissed before. We might move to Carthage though.

**Comment by irodrigo17** [comment]
@duemunk Sorry, I can't find any other issue or pull request that addresses this. Can you provide some insights about why has this been dismissed before? Pushing the dependencies kind of misses the whole point of dependency management IMO, but of course there can be valid reasons to do it.

I'm actually working on integrating TravisCI and then I plan to fix the current tests and add some more to improve coverage, this was just a previous step just to tidy up things a bit. 

I think you have a great project here that could potentially get a lot of support from the open source community, so I'd like to help build a more robust development infrastructure, if that makes sense. Of course, I'll be happy to switch to other tasks if you think that's better.

**Comment by duemunk** [comment]
@irodrigo17 We're still trying to catch up with the overwhelming amount of interest :) 

Don't be sorry about helping out. Any help is welcome! We're still trying to figure out how to make the project truly open source. It will take a while, but hopefully we can get there. 
Pull request are usually much more worth than issues, but in the beginning I think issues would be easier, since we can discuss why things are the way to go or not.

As for CocoaPods, I like to use it as an integration manager, but I don't want to be dependant on CocoaPods to work, for a project to be able to build. Additionally, I like being able to have a repo that is just clone-build-run.

**Comment by Thelle** [comment]
Great @irodrigo17 - thank you for your efforts! - Amen for clone-build-run! :+1:

**Pull request closed without merging**
